input Pagination {
	page: Int = 1
	limit: Int = 2
}

type Query {
    orderProducts(
        order_id: ID
        product_id: ID
        pagination: Pagination = {}
    ): [OrderProduct!]!
}

type OrderProduct {
    order_id: ID!
    product_id: ID!
    count: Int!
}

type Mutation {
    addOrderProducts( order_id: ID! product_id: ID! count: Int): Response!

    updateOrderProducts( order_id: ID! product_id: ID! count: Int ): Response!
    
    deleteOrderProducts(order_id: ID! product_id: ID! ): Response!
}

type Response {
    status: Int!
    message: String!
    orderProduct: OrderProduct
}