input Pagination {
	page: Int = 1
	limit: Int = 10
}

type Query {
    orders(
        order_id: ID
        user_id: ID
        isPaid: Boolean
        order_created_at: String
        pagination: Pagination = {}
    ): [Order!]!
}

type Order {
    order_id: ID!
    user_id: ID!
    isPaid: Boolean
}

type Mutation {
    addOrder(user_id: ID! isPaid: Boolean!): Response!
    updateOrder(order_id: Int! isPaid: Boolean user_id: Int ): Response!
    deleteOrder(order_id: Int! ): Response!
}

type Response {
    status: Int!
    message: String!
    order: Order
}