input Pagination {
	page: Int = 1
	limit: Int = 10
}

type Query {
    orders(
        order_id: ID
        user_id: ID
        isPaid: String
        order_created_at: String
        pagination: Pagination = {}
    ): [Order!]!
}

type Order {
    order_id: ID!
    user_id: ID!
    isPaid: String
    order_created_at: Any
    count: [Int]
    price: [Int]
    products: [String]
    summary: Int
}

type Mutation {
    addOrder(user_id: ID isPaid: String): Response!
    updateOrder(order_id: Int! isPaid: String user_id: Int ): Response!
    deleteOrder(order_id: Int! ): Response!
}

type Response {
    status: Int!
    message: String!
    order: Order
}