input Pagination {
	page: Int = 1
	limit: Int = 2
}

type Query {
    users(
        user_id: ID
        search: String
        pagination: Pagination = {}
    ): [User!]!
}

type User {
    user_id: ID!
    username: String!
    contact: String!
    email: String!
    role: String!
}

type Mutation {
    register(username: String! 
            password: String! 
            contact: String! 
            email: String! 
            role: String! ): Response!

    login(username: String! 
          password: String! ): Response!

    updateUser(user_id: Int! 
               username: String
               password: String
               contact: String
               email: String
               role: String ): Response!
}

type Response {
    status: Int!
    message: String!
    user: User
}