input Pagination {
	page: Int = 1
	limit: Int = 2
}

scalar Upload
scalar File
scalar Any

type Query {
    products(
        product_id: ID
        search: String
        price: Int
        category_id: ID
        pagination: Pagination = {}
    ): [Product!]!
}

type Product {
    product_id: ID!
    product_name: String!
    price: Int!
    short_desc: String!
    long_desc: String!
    file: Any!
    imgUrl: String
    category_id: ID!
}


type Mutation {
    addProduct(product_name: String! price: Int! short_desc: String! long_desc: String! file: Upload! category_id: Int!): Response!

    updateProduct( product_id: Int! 
                product_name: String
                price: Int
                short_desc: String
                long_desc: String
                category_id: ID
                 ): Response!

    deleteProduct(product_id: Int! ): Response!
}

type Response {
    status: Int!
    message: String!
    product: Product
}


type File {
    filename: String
    mimetype: String
    encoding: String
}