input Pagination {
	page: Int = 1
	limit: Int = 2
}

scalar Upload

type Query {
    products(
        product_id: ID
        search: String
        price: Int
        category_id: ID
        pagination: Pagination = {}
    ): [Product!]!
}

type Product {
    product_id: ID!
    name: String!
    price: Int!
    short_desc: String!
    long_desc: String!
    picture: String!
    category_id: ID!
}

type Mutation {
    addProduct( name: String! 
                price: String! 
                short_desc: String! 
                long_desc: String! 
                picture: Upload!
                category_id: ID!): Response!

    updateProduct( product_id: Int! 
                name: String
                price: Int
                short_desc: String
                long_desc: String
                category_id: ID
                 ): Response!

    deleteProduct(product_id: Int! ): Response!
}

type Response {
    status: Int!
    message: String!
    product: Product
}